# SQL Interview Questions

# Employees Hired in the Last Duration

In [1]:
from dotenv import load_dotenv
import os
import mysql.connector
import pandas as pd

In [2]:
load_dotenv()

True

In [3]:
conn = mysql.connector.connect(
    user=os.getenv("MYSQL_USER"),
    host=os.getenv("MYSQL_HOST"),
    port=os.getenv("MYSQL_PORT"),
    password=os.getenv("MYSQL_PASSWORD")
)
print("Connected to MySQL Server successfully")

Connected to MySQL Server successfully

In [4]:
cursor = conn.cursor()

In [5]:
cursor.execute("SHOW DATABASES")

In [6]:
databases = cursor.fetchall()

In [7]:
databases

[('bmrc',),
 ('coalesce_db',),
 ('collections',),
 ('company_db',),
 ('cte_db',),
 ('groupby_db',),
 ('information_schema',),
 ('interviews',),
 ('joins_db',),
 ('kjm_elect_locos_db',),
 ('mysql',),
 ('normalization_db',),
 ('nth_highest_salary_int_db',),
 ('organization_hierarchy_int_db',),
 ('performance_schema',),
 ('recursive_cte_db',),
 ('self_joins_db',),
 ('stored_procedures_db',),
 ('sys',),
 ('unions_db',),
 ('window_functions_db',)]

In [8]:
[database_tup[0] for database_tup in databases]

['bmrc',
 'coalesce_db',
 'collections',
 'company_db',
 'cte_db',
 'groupby_db',
 'information_schema',
 'interviews',
 'joins_db',
 'kjm_elect_locos_db',
 'mysql',
 'normalization_db',
 'nth_highest_salary_int_db',
 'organization_hierarchy_int_db',
 'performance_schema',
 'recursive_cte_db',
 'self_joins_db',
 'stored_procedures_db',
 'sys',
 'unions_db',
 'window_functions_db']

In [9]:
cursor.execute("USE interviews")

In [10]:
cursor.execute("SHOW TABLES")

In [11]:
tables = cursor.fetchall()

In [12]:
tables

[('dailysales',), ('employeestbl_hired_in_last_duration',)]

In [13]:
[table_tup[0] for table_tup in tables]

['dailysales', 'employeestbl_hired_in_last_duration']

In [14]:
query = """
create table if not exists employeesTbl_hired_in_last_duration
(
    id int primary key auto_increment,
    first_name varchar(50),
    last_name varchar(50),
    gender varchar(50),
    salary int,
    hire_date datetime
)
"""

In [15]:
cursor.execute(query)

In [16]:
query = """
insert into employeesTbl_hired_in_last_duration 
(first_name, last_name, gender, salary, hire_date)
values
('Amit','Sharma','Male',60000,'2026-02-14'),
('Rahul','Verma','Male',45000,'2025-11-03'),
('Suresh','Reddy','Male',70000,'2024-09-22'),
('Vikram','Iyer','Male',45000,'2026-01-18'),
('Priya','Nair','Female',30000,'2025-03-10'),
('Anjali','Mehta','Female',35000,'2024-12-05'),
('Karthik','Subramanian','Male',80000,'2025-08-27'),
('Ravi','Yadav','Male',5000,'2024-06-14'),
('Sneha','Kulkarni','Female',5000,'2026-02-01'),
('Arjun','Patel','Male',6000,'2024-04-19'),
('Deepak','Singh','Male',7000,'2025-07-11'),
('Manoj','Gupta','Male',7000,'2026-01-30'),
('Nikhil','Joshi','Male',6500,'2024-10-09'),
('Rohit','Agarwal','Male',5500,'2025-05-21'),
('Pooja','Chopra','Female',4500,'2026-02-25'),
('Sunil','Mishra','Male',3500,'2024-08-17'),
('Imran','Khan','Male',8500,'2025-09-13'),
('Neha','Bansal','Female',6500,'2024-11-28'),
('Kavita','Shah','Female',4500,'2025-12-19'),
('Tarun','Malhotra','Male',3500,'2026-03-05'),
('Faizan','Ali','Male',6500,'2024-07-07'),
('Varun','Kapoor','Male',4900,'2025-10-02'),
('Gaurav','Saxena','Male',2600,'2024-05-15'),
('Ajay','Dubey','Male',2900,'2025-06-30'),
('Salman','Ansari','Male',3800,'2026-01-08'),
('Harish','Pillai','Male',3100,'2024-09-03')
"""

In [17]:
cursor.execute(query)

In [18]:
cursor.execute("select * from employeesTbl_hired_in_last_duration")
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]

In [19]:
pd.DataFrame(employees, columns=headers)

     id first_name    last_name  gender  salary  hire_date
0   209       Amit       Sharma    Male   60000 2026-02-14
1   210      Rahul        Verma    Male   45000 2025-11-03
2   211     Suresh        Reddy    Male   70000 2024-09-22
3   212     Vikram         Iyer    Male   45000 2026-01-18
4   213      Priya         Nair  Female   30000 2025-03-10
5   214     Anjali        Mehta  Female   35000 2024-12-05
6   215    Karthik  Subramanian    Male   80000 2025-08-27
7   216       Ravi        Yadav    Male    5000 2024-06-14
8   217      Sneha     Kulkarni  Female    5000 2026-02-01
9   218      Arjun        Patel    Male    6000 2024-04-19
10  219     Deepak        Singh    Male    7000 2025-07-11
11  220      Manoj        Gupta    Male    7000 2026-01-30
12  221     Nikhil        Joshi    Male    6500 2024-10-09
13  222      Rohit      Agarwal    Male    5500 2025-05-21
14  223      Pooja       Chopra  Female    4500 2026-02-25
15  224      Sunil       Mishra    Male    3500 2024-08-17
16  225      Imran         Khan    Male    8500 2025-09-13
17  226       Neha       Bansal  Female    6500 2024-11-28
18  227     Kavita         Shah  Female    4500 2025-12-19
19  228      Tarun     Malhotra    Male    3500 2026-03-05
20  229     Faizan          Ali    Male    6500 2024-07-07
21  230      Varun       Kapoor    Male    4900 2025-10-02
22  231     Gaurav       Saxena    Male    2600 2024-05-15
23  232       Ajay        Dubey    Male    2900 2025-06-30
24  233     Salman       Ansari    Male    3800 2026-01-08
25  234     Harish       Pillai    Male    3100 2024-09-03

## Employees hired in the last 75 days

In [20]:
query = """
select *, datediff(curdate(), hire_date) as diff
from employeesTbl_hired_in_last_duration
order by hire_date desc
"""

cursor.execute(query)
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]
display(pd.DataFrame(employees, columns=headers))

     id first_name    last_name  gender  salary  hire_date  diff
0   228      Tarun     Malhotra    Male    3500 2026-03-05    38
1   223      Pooja       Chopra  Female    4500 2026-02-25    46
2   209       Amit       Sharma    Male   60000 2026-02-14    57
3   217      Sneha     Kulkarni  Female    5000 2026-02-01    70
4   220      Manoj        Gupta    Male    7000 2026-01-30    72
5   212     Vikram         Iyer    Male   45000 2026-01-18    84
6   233     Salman       Ansari    Male    3800 2026-01-08    94
7   227     Kavita         Shah  Female    4500 2025-12-19   114
8   210      Rahul        Verma    Male   45000 2025-11-03   160
9   230      Varun       Kapoor    Male    4900 2025-10-02   192
10  225      Imran         Khan    Male    8500 2025-09-13   211
11  215    Karthik  Subramanian    Male   80000 2025-08-27   228
12  219     Deepak        Singh    Male    7000 2025-07-11   275
13  232       Ajay        Dubey    Male    2900 2025-06-30   286
14  222      Rohit      Agarwal    Male    5500 2025-05-21   326
15  213      Priya         Nair  Female   30000 2025-03-10   398
16  214     Anjali        Mehta  Female   35000 2024-12-05   493
17  226       Neha       Bansal  Female    6500 2024-11-28   500
18  221     Nikhil        Joshi    Male    6500 2024-10-09   550
19  211     Suresh        Reddy    Male   70000 2024-09-22   567
20  234     Harish       Pillai    Male    3100 2024-09-03   586
21  224      Sunil       Mishra    Male    3500 2024-08-17   603
22  229     Faizan          Ali    Male    6500 2024-07-07   644
23  216       Ravi        Yadav    Male    5000 2024-06-14   667
24  231     Gaurav       Saxena    Male    2600 2024-05-15   697
25  218      Arjun        Patel    Male    6000 2024-04-19   723

In [21]:
query = """
select *, datediff(curdate(), hire_date) as diff
from employeesTbl_hired_in_last_duration
where datediff(curdate(), hire_date) <= 75
order by hire_date desc
"""

cursor.execute(query)
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]
display(pd.DataFrame(employees, columns=headers))

    id first_name last_name  gender  salary  hire_date  diff
0  228      Tarun  Malhotra    Male    3500 2026-03-05    38
1  223      Pooja    Chopra  Female    4500 2026-02-25    46
2  209       Amit    Sharma    Male   60000 2026-02-14    57
3  217      Sneha  Kulkarni  Female    5000 2026-02-01    70
4  220      Manoj     Gupta    Male    7000 2026-01-30    72

In [22]:
query = """
select *, timestampdiff(day, hire_date, curdate()) as diff
from employeesTbl_hired_in_last_duration
order by hire_date desc
"""
cursor.execute(query)
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]
display(pd.DataFrame(employees, columns=headers))

     id first_name    last_name  gender  salary  hire_date  diff
0   228      Tarun     Malhotra    Male    3500 2026-03-05    38
1   223      Pooja       Chopra  Female    4500 2026-02-25    46
2   209       Amit       Sharma    Male   60000 2026-02-14    57
3   217      Sneha     Kulkarni  Female    5000 2026-02-01    70
4   220      Manoj        Gupta    Male    7000 2026-01-30    72
5   212     Vikram         Iyer    Male   45000 2026-01-18    84
6   233     Salman       Ansari    Male    3800 2026-01-08    94
7   227     Kavita         Shah  Female    4500 2025-12-19   114
8   210      Rahul        Verma    Male   45000 2025-11-03   160
9   230      Varun       Kapoor    Male    4900 2025-10-02   192
10  225      Imran         Khan    Male    8500 2025-09-13   211
11  215    Karthik  Subramanian    Male   80000 2025-08-27   228
12  219     Deepak        Singh    Male    7000 2025-07-11   275
13  232       Ajay        Dubey    Male    2900 2025-06-30   286
14  222      Rohit      Agarwal    Male    5500 2025-05-21   326
15  213      Priya         Nair  Female   30000 2025-03-10   398
16  214     Anjali        Mehta  Female   35000 2024-12-05   493
17  226       Neha       Bansal  Female    6500 2024-11-28   500
18  221     Nikhil        Joshi    Male    6500 2024-10-09   550
19  211     Suresh        Reddy    Male   70000 2024-09-22   567
20  234     Harish       Pillai    Male    3100 2024-09-03   586
21  224      Sunil       Mishra    Male    3500 2024-08-17   603
22  229     Faizan          Ali    Male    6500 2024-07-07   644
23  216       Ravi        Yadav    Male    5000 2024-06-14   667
24  231     Gaurav       Saxena    Male    2600 2024-05-15   697
25  218      Arjun        Patel    Male    6000 2024-04-19   723

In [23]:
query = """
select *, timestampdiff(day, hire_date, curdate()) as diff
from employeesTbl_hired_in_last_duration
where timestampdiff(day, hire_date, curdate()) <= 75
order by hire_date desc
"""
cursor.execute(query)
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]
display(pd.DataFrame(employees, columns=headers))

    id first_name last_name  gender  salary  hire_date  diff
0  228      Tarun  Malhotra    Male    3500 2026-03-05    38
1  223      Pooja    Chopra  Female    4500 2026-02-25    46
2  209       Amit    Sharma    Male   60000 2026-02-14    57
3  217      Sneha  Kulkarni  Female    5000 2026-02-01    70
4  220      Manoj     Gupta    Male    7000 2026-01-30    72

## Employees hired in the last 3 months

In [24]:
query = """
select *, timestampdiff(month, hire_date, curdate()) as diff
from employeesTbl_hired_in_last_duration
where timestampdiff(month, hire_date, curdate()) <= 3
order by hire_date desc
"""
cursor.execute(query)
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]
display(pd.DataFrame(employees, columns=headers))

    id first_name last_name  gender  salary  hire_date  diff
0  228      Tarun  Malhotra    Male    3500 2026-03-05     1
1  223      Pooja    Chopra  Female    4500 2026-02-25     1
2  209       Amit    Sharma    Male   60000 2026-02-14     1
3  217      Sneha  Kulkarni  Female    5000 2026-02-01     2
4  220      Manoj     Gupta    Male    7000 2026-01-30     2
5  212     Vikram      Iyer    Male   45000 2026-01-18     2
6  233     Salman    Ansari    Male    3800 2026-01-08     3
7  227     Kavita      Shah  Female    4500 2025-12-19     3

## Employees hired in the last 1 year

In [25]:
query = """
select *,timestampdiff(year, hire_date, curdate()) as diff
from employeesTbl_hired_in_last_duration
where hire_date >= curdate() - interval 1 year
order by hire_date desc
"""
cursor.execute(query)
employees = cursor.fetchall()
headers = [tup[0] for tup in cursor.description]
display(pd.DataFrame(employees, columns=headers))

     id first_name    last_name  gender  salary  hire_date  diff
0   228      Tarun     Malhotra    Male    3500 2026-03-05     0
1   223      Pooja       Chopra  Female    4500 2026-02-25     0
2   209       Amit       Sharma    Male   60000 2026-02-14     0
3   217      Sneha     Kulkarni  Female    5000 2026-02-01     0
4   220      Manoj        Gupta    Male    7000 2026-01-30     0
5   212     Vikram         Iyer    Male   45000 2026-01-18     0
6   233     Salman       Ansari    Male    3800 2026-01-08     0
7   227     Kavita         Shah  Female    4500 2025-12-19     0
8   210      Rahul        Verma    Male   45000 2025-11-03     0
9   230      Varun       Kapoor    Male    4900 2025-10-02     0
10  225      Imran         Khan    Male    8500 2025-09-13     0
11  215    Karthik  Subramanian    Male   80000 2025-08-27     0
12  219     Deepak        Singh    Male    7000 2025-07-11     0
13  232       Ajay        Dubey    Male    2900 2025-06-30     0
14  222      Rohit      Agarwal    Male    5500 2025-05-21     0